"use client";

import { motion } from "framer-motion";
import { useRouter } from "next/navigation";
import dynamic from "next/dynamic";
import Cursor from "@/components/Cursor";
import ScanlineOverlay from "@/components/ScanlineOverlay";
import GlitchText from "@/components/GlitchText";

const Skull3D = dynamic(() => import("@/components/Skull3D"), { ssr: false });

const STACK = [
  { name: "Next.js 14", role: "Framework + API Routes" },
  { name: "TypeScript", role: "Type safety" },
  { name: "Tailwind CSS", role: "Noir UI system" },
  { name: "Framer Motion", role: "Animations" },
  { name: "Claude / Gemini", role: "AI narrative (dual cascade)" },
  { name: "0G Storage", role: "Permanent fragment storage" },
  { name: "0G Chain", role: "On-chain verification" },
  { name: "RainbowKit", role: "Wallet connect (MetaMask)" },
  { name: "Web Audio API", role: "Generative soundtrack" },
  { name: "CSS 3D + SVG", role: "Skull visualization" },
];

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <motion.section initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }} className="mb-16">
      <h2 className="font-display text-sm text-noir-accent tracking-[0.2em] uppercase mb-6">{title}</h2>
      {children}
    </motion.section>
  );
}

export default function JudgesPage() {
  const router = useRouter();

  return (
    <div className="min-h-screen relative">
      <Cursor />
      <ScanlineOverlay />

      {/* Header */}
      <header className="flex items-center justify-between p-4 sm:p-6 border-b border-noir-border/20 relative z-50">
        <button onClick={() => router.push("/")}
          className="font-display text-lg text-noir-text tracking-[0.15em] hover:text-noir-accent transition-colors">
          <GlitchText text="MONGLI" intensity="low" />
        </button>
        <span className="font-body text-[9px] text-noir-muted tracking-[0.3em] uppercase">
          Technical Overview
        </span>
      </header>

      <main className="max-w-3xl mx-auto px-4 sm:px-8 py-12">
        {/* Hero */}
        <div className="text-center mb-16">
          <div className="w-[150px] h-[150px] mx-auto mb-6">
            <Skull3D scene="void" className="w-full h-full" />
          </div>
          <h1 className="font-display text-2xl sm:text-3xl text-noir-text tracking-wider mb-2">
            MONGLI GAME
          </h1>
          <p className="font-body text-xs text-noir-accent tracking-[0.3em] uppercase mb-4">
            Zero Cup 2026 · 0G Labs Hackathon
          </p>
          <div className="flex items-center justify-center gap-2 flex-wrap">
            <span className="px-2 py-1 border border-noir-accent/40 text-[9px] font-body text-noir-accent">Built on 0G</span>
            <span className="px-2 py-1 border border-blue-500/40 text-[9px] font-body text-blue-400">AI-Native</span>
            <span className="px-2 py-1 border border-purple-500/40 text-[9px] font-body text-purple-400">Vibe Coded</span>
          </div>
        </div>

        {/* Section 1: The Pitch */}
        <Section title="The Pitch">
          <div className="manila-folder p-6 text-center">
            <p className="font-display text-lg text-noir-text mb-4">
              AI writes your story. 0G stores it forever.
            </p>
            <p className="font-body text-xs text-noir-muted mb-6 max-w-md mx-auto">
              A noir amnesia game where every memory fragment is generated by AI (Claude/Gemini),
              stored permanently on 0G Storage, and verified on 0G Chain.
              Your identity is determined by your choices.
            </p>
            <motion.button onClick={() => router.push("/")}
              whileHover={{ scale: 1.05 }}
              className="px-8 py-3 border-2 border-noir-accent text-noir-accent font-display text-sm tracking-wider uxpm-press">
              Play the game →
            </motion.button>
            <motion.button onClick={() => router.push("/trailer")}
              whileHover={{ scale: 1.05 }}
              className="px-6 py-2.5 border border-noir-border text-noir-muted font-display text-xs tracking-wider uxpm-press hover:text-noir-accent">
              Ver trailer → (90s, no wallet)
            </motion.button>
          </div>
        </Section>

        {/* Section 2: Why 0G is not bolt-on */}
        <Section title="Why 0G is NOT a bolt-on">
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            {[
              {
                icon: "💾", title: "0G Storage",
                desc: "Every memory fragment is stored permanently. Without it, player histories are lost.",
                code: "await uploadFragment(fragment)\n// → SHA-256 hash → 0G blob",
                why: "Without 0G: memories deleted on browser close. With 0G: immutable forever.",
              },
              {
                icon: "⛓", title: "0G Chain",
                desc: "Every act completion triggers an on-chain event via MongliMemory.sol.",
                code: "saveFragment(hash, actId)\n// → FragmentSaved event",
                why: "Contract: 0x81B6...E9f8 on Galileo Testnet",
              },
              {
                icon: "🧠", title: "0G Compute",
                desc: "Next: narrative AI inference directly on 0G Compute for full decentralization.",
                code: "// Future: 0G Compute API\n// → Decentralized AI inference",
                why: "Roadmap: move AI from centralized APIs to 0G Compute.",
              },
            ].map((card) => (
              <div key={card.title} className="manila-folder p-4">
                <span className="text-xl mb-2 block">{card.icon}</span>
                <h3 className="font-display text-xs text-noir-text mb-2">{card.title}</h3>
                <p className="font-body text-[10px] text-noir-muted mb-3">{card.desc}</p>
                <pre className="font-mono text-[8px] text-green-500/60 bg-noir-bg/50 p-2 mb-2 overflow-x-auto">
                  {card.code}
                </pre>
                <p className="font-body text-[9px] text-noir-accent/60 italic">{card.why}</p>
              </div>
            ))}
          </div>
        </Section>

        {/* Section 3: Architecture */}
        <Section title="Architecture">
          <pre className="font-mono text-[10px] sm:text-[11px] text-noir-text/70 bg-noir-card p-4 sm:p-6 border border-noir-border/30 overflow-x-auto leading-relaxed">
{`Player → MetaMask → Next.js API → Claude/Gemini AI
                        │               │
                        │         Fragment JSON
                        │               │
                        ▼               ▼
                   0G Storage    ← SHA-256 hash
                        │
                        ▼
                   0G Chain (MongliMemory.sol)
                        │
                        ▼
                   FragmentSaved event

   ┌──────────────────────────┐
   │  5 Acts × 3 Fragments   │
   │  1 Decision per Act      │
   │  1 TX per Act on 0G      │
   │  Save/Load from 0G       │
   └──────────────────────────┘`}
          </pre>
        </Section>

        {/* Section 4: Stack & Stats */}
        <Section title="Stack & Stats">
          <div className="grid grid-cols-2 sm:grid-cols-5 gap-2 mb-6">
            {STACK.map((s) => (
              <div key={s.name} className="border border-noir-border/30 p-2 text-center">
                <p className="font-body text-[10px] text-noir-text">{s.name}</p>
                <p className="font-body text-[8px] text-noir-muted">{s.role}</p>
              </div>
            ))}
          </div>
          <div className="flex flex-wrap justify-center gap-4 text-center">
            {[
              { num: "70+", label: "files" },
              { num: "22", label: "routes" },
              { num: "1", label: "smart contract" },
              { num: "5", label: "game modes" },
              { num: "20", label: "features" },
            ].map((s) => (
              <div key={s.label}>
                <p className="font-display text-xl text-noir-accent">{s.num}</p>
                <p className="text-[8px] font-body text-noir-muted uppercase">{s.label}</p>
              </div>
            ))}
          </div>
        </Section>

        {/* Section 5: Live Contract */}
        <Section title="Live Contract">
          <div className="manila-folder p-5 text-center">
            <p className="font-mono text-xs text-noir-accent mb-2">MongliMemory.sol</p>
            <p className="font-mono text-[10px] text-noir-muted mb-4">
              0x81B600E7ACE4CEe5D698C39368B615A732d0E9f8
            </p>
            <a href="https://chainscan-galileo.0g.ai/address/0x81B600E7ACE4CEe5D698C39368B615A732d0E9f8"
              target="_blank" rel="noopener noreferrer"
              className="px-4 py-2 border border-noir-accent text-noir-accent font-body text-xs uxpm-press inline-block hover:bg-noir-accent/10">
              View on 0G Explorer →
            </a>
          </div>
        </Section>

        {/* Section 6: Vibe Coding */}
        <Section title="The Vibe Coding Process">
          <p className="font-body text-xs text-noir-muted leading-relaxed mb-4">
            Built with Claude Code (AI-assisted development). 11 development blocks spanning
            visual effects, narrative engine, blockchain integration, audio, and UX.
            Human-directed, AI-accelerated.
          </p>
          <a href="https://github.com/ALFA117/Mongli_Game" target="_blank" rel="noopener noreferrer"
            className="font-body text-xs text-noir-accent hover:underline">
            View complete source on GitHub →
          </a>
        </Section>

        {/* Footer */}
        <div className="text-center border-t border-noir-border/20 pt-8">
          <p className="font-body text-xs text-noir-muted">Edgar Lopez Baeza · @ALFA_EDG</p>
          <p className="font-body text-[9px] text-noir-muted/40 mt-1">Zero Cup 2026 · 0G Labs</p>
          <div className="flex items-center justify-center gap-4 mt-4 text-[9px] font-body text-noir-muted/40">
            <a href="https://mongli-game.vercel.app" className="hover:text-noir-accent">Live Game</a>
            <a href="https://github.com/ALFA117/Mongli_Game" target="_blank" rel="noopener noreferrer" className="hover:text-noir-accent">GitHub</a>
            <button onClick={() => router.push("/gallery")} className="hover:text-noir-accent">Gallery</button>
          </div>
        </div>
      </main>
    </div>
  );
}
